// products list
export const PRODUCTS_LIST_REQUEST = "PRODUCTS_LIST_REQUEST" 
export const PRODUCTS_LIST_SUCCESS = "PRODUCTS_LIST_SUCCESS"
export const PRODUCTS_LIST_FAIL = "PRODUCTS_LIST_FAIL"

// product details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST" 
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

// create product
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST" 
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS" 
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL" 
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET" 

// update product
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST" 
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS" 
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL" 
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET" 

// delete product
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST" 
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS" 
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL" 
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET" 

// check token validation
export const CHECK_TOKEN_VALID_REQUEST = "CHECK_TOKEN_VALID_REQUEST"
export const CHECK_TOKEN_VALID_SUCCESS = "CHECK_TOKEN_VALID_SUCCESS"
export const CHECK_TOKEN_VALID_FAIL = "CHECK_TOKEN_VALID_FAIL"
export const CHECK_TOKEN_VALID_RESET = "CHECK_TOKEN_VALID_RESET"
// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user info/details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

// user update details
export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST"
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS"
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL"
export const UPDATE_USER_DETAILS_RESET = "UPDATE_USER_DETAILS_RESET"

// delete user account
export const DELETE_USER_ACCOUNT_REQUEST = "DELETE_USER_ACCOUNT_REQUEST" 
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS" 
export const DELETE_USER_ACCOUNT_FAIL = "DELETE_USER_ACCOUNT_FAIL" 
export const DELETE_USER_ACCOUNT_RESET = "DELETE_USER_ACCOUNT_RESET" 

// user all address
export const GET_USER_ALL_ADDRESSES_REQUEST = "GET_USER_ALL_ADDRESSES_REQUEST"
export const GET_USER_ALL_ADDRESSES_SUCCESS = "GET_USER_ALL_ADDRESSES_SUCCESS"
export const GET_USER_ALL_ADDRESSES_FAIL = "GET_USER_ALL_ADDRESSES_FAIL"

// user single address details
export const GET_SINGLE_ADDRESS_REQUEST = "GET_SINGLE_ADDRESS_REQUEST"
export const GET_SINGLE_ADDRESS_SUCCESS = "GET_SINGLE_ADDRESS_SUCCESS"
export const GET_SINGLE_ADDRESS_FAIL = "GET_SINGLE_ADDRESS_FAIL"
export const GET_SINGLE_ADDRESS_RESET = "GET_SINGLE_ADDRESS_RESET"

// create address
export const CREATE_USER_ADDRESS_REQUEST = "CREATE_USER_ADDRESS_REQUEST"
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS"
export const CREATE_USER_ADDRESS_FAIL = "CREATE_USER_ADDRESS_FAIL"
export const CREATE_USER_ADDRESS_RESET = "CREATE_USER_ADDRESS_RESET"

// update address
export const UPDATE_USER_ADDRESS_REQUEST = "UPDATE_USER_ADDRESS_REQUEST"
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS"
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL"
export const UPDATE_USER_ADDRESS_RESET = "UPDATE_USER_ADDRESS_RESET"

// delete user address
export const DELETE_USER_ADDRESS_REQUEST = "DELETE_USER_ADDRESS_REQUEST"
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS"
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL"
export const DELETE_USER_ADDRESS_RESET = "DELETE_USER_ADDRESS_RESET"

// all orders list
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

// change order delivery status
export const CHANGE_DELIVERY_STATUS_REQUEST = "CHANGE_DELIVERY_STATUS_REQUEST"
export const CHANGE_DELIVERY_STATUS_SUCCESS = "CHANGE_DELIVERY_STATUS_SUCCESS"
export const CHANGE_DELIVERY_STATUS_FAIL = "CHANGE_DELIVERY_STATUS_FAIL"
export const CHANGE_DELIVERY_STATUS_RESET = "CHANGE_DELIVERY_STATUS_RESET"

// create mpesa transaction
export const MPESA_TRANSACTION_RESET = "MPESA_CREATE_RESET"

// STK push status
export const MPESA_STK_PUSH_REQUEST = "MPESA_STK_PUSH_REQUEST"
export const MPESA_STK_PUSH_FAIL = "MPESA_STK_PUSH_FAIL"
export const MPESA_STK_PUSH_SUCCESS = "MPESA_STK_PUSH_SUCCESS"

// call-back handler status
export const MPESA_CALLBACK_HANDLER_REQUEST = "MPESA_CALLBACK_HANDLER_REQUEST"
export const MPESA_CALLBACK_HANDLER_FAIL = "MPESA_CALLBACK_HANDLER_FAIL"
export const MPESA_CALLBACK_HANDLER_SUCCESS = "MPESA_CALLBACK_HANDLER_SUCCESS"